### ISSUE TITLE
Only decodes one object

### ISSUE THREAD

**Issue by Bilge** [mlsomers/LsMsgPack#5]
Given the input file: [lol.txt](https://github.com/mlsomers/LsMsgPack/files/6028691/lol.txt), decodes as a single fixint with value 0, ignoring all the following object bytes. Should continue decoding the rest of the file.

**Comment by mlsomers** [comment]
Ok so if I have analysed this correctly, the 2nd byte is 0x92, array of 2 unsigned shorts (597 and 492)..
Then 0x90 (an empty array), two NULL's
Then a Fixed string of 1 byte which is missing from the file...

Not sure why it isn't parsing the arrays and nulls, it should only fail at the last string, will have to debug this one (and add it to the test suite).

I'll try to look into this shortly (maybe this weekend).
Thanks for reporting.

**Comment by Bilge** [comment]
I see you edited your post. I was going to point out those nulls are not nulls. Nevertheless, you still reference nulls in the following paragraph 😉 

I assumed it was just because it was only designed to process a single object, like so many poorly conceived MessagePack implementations that treat MessagePack like JSON, but your reaction of surprise suggests otherwise.

**Comment by mlsomers** [comment]
Turns out I have always used arrays and maps to store items in.
Had to add a new container type (MpRoot) to hold the items and separate read and write methods (PackMultiple and UnpackMultiple) to support this. The original Pack will make an array if multiple objects are passed (and I don't want to break it).

**Comment by mlsomers** [comment]
Added a pre-release with this fix.
